In [1]:
import numpy as np
import pandas as pd

In [2]:
funding_2025 = pd.read_csv("indian_startup_funding_2020_2025_sample.csv")
funding_2015 = pd.read_csv("startup_funding.csv")

In [3]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [4]:
funding_2015.tail()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
funding_2015 = funding_2015.drop(['Sr No', 'Remarks'], axis=1)

In [6]:
funding_2015.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [7]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [8]:
funding_2015.rename(
    columns={
        "Date dd/mm/yyyy":'Date',
        'Startup Name':'Startup',
        'Industry Vertical':'Industry',
        'City  Location':'City',
        'Investors Name':'Investors',
        'InvestmentType':'Investment Type'},
    inplace=True)

In [9]:
funding_2025.rename(columns = {'InvestmentAmount_USD':'Amount in USD', 'InvestmentType':'Investment Type'}, inplace=True)

In [10]:
funding_2015.columns

Index(['Date', 'Startup', 'Industry', 'SubVertical', 'City', 'Investors',
       'InvestmentnType', 'Amount in USD'],
      dtype='object')

In [11]:
funding_2025.columns

Index(['Startup', 'Industry', 'SubVertical', 'City', 'Investors',
       'Investment Type', 'Amount in USD', 'Date'],
      dtype='object')

In [12]:
funding_2025['Date'] = pd.to_datetime(
    funding_2025['Date'],
    format='%d-%m-%Y'
)

funding_2025.sort_values('Date', ascending=False, inplace=True)

In [13]:
funding_2025['Date'] = funding_2025['Date'].dt.strftime('%d/%m/%Y')

In [14]:
funding = pd.concat([funding_2025, funding_2015])

In [21]:
funding.iloc[1292]

Startup                                                     Loan Tap
Industry                                           Consumer Internet
SubVertical        Online Lending Platform For Salaried Professio...
City                                                          Mumbai
Investors          Shunwei Capital, Tuscan Ventures, Ashish Goenk...
Investment Type                                                  NaN
Amount in USD                                              62,50,000
Date                                                       05/072018
InvestmentnType                                       Private Equity
Name: 192, dtype: object

In [16]:
funding.head()

,Startup,Industry,SubVertical,City,Investors,Investment Type,Amount in USD,Date,InvestmentnType
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,30/06/2025,NaN
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,29/06/2025,NaN
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,27/06/2025,NaN
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,27/06/2025,NaN
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,24/06/2025,NaN

In [17]:
funding.tail()

,Startup,Industry,SubVertical,City,Investors,Investment Type,Amount in USD,Date,InvestmentnType
3039,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,NaN,"45,00,000",29/01/2015,Private Equity
3040,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,NaN,"8,25,000",29/01/2015,Private Equity
3041,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",NaN,"15,00,000",30/01/2015,Private Equity
3042,Simplotel,NaN,NaN,NaN,MakeMyTrip,NaN,NaN,30/01/2015,Private Equity
3043,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,NaN,"1,40,000",31/01/2015,Seed Funding

In [18]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Startup          4144 non-null   object
 1   Industry         3973 non-null   object
 2   SubVertical      3208 non-null   object
 3   City             3964 non-null   object
 4   Investors        4120 non-null   object
 5   Investment Type  1100 non-null   object
 6   Amount in USD    3184 non-null   object
 7   Date             4144 non-null   object
 8   InvestmentnType  3040 non-null   object
dtypes: object(9)
memory usage: 323.8+ KB